firstdjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),
    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),
    url(r'^downloads', views.downloads, name='downloads'),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    # template = loader.get_template('music/index.html')
    context = {
        'all_albums': all_albums,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'music/index.html', context)


def details(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    # try:
    #     album = Album.objects.get(id=album_id)
    # except Album.DoesNotExist:
    #     raise Http404("Album does not exist")
    return render(request, 'music/details.html', {'album': album})


def favourite(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    try:
        selected_song = album.song_set.get(id=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/details.html', {
            'error_message': 'Please select a valid option',
            'album': album
        })
    if selected_song.is_favourite is False:
        selected_song.is_favourite = True
        selected_song.save()
    return render(request, 'music/details.html', {'album': album})


def downloads(request):
    return HttpResponse("<h1>This is the Music Download Page</h1>")

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Metamorphous">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'music:index' %}" class="navbar-brand">VIBERR</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Music
                    </a>
                </li>
            </ul>

            <form action="#" class="navbar-form navbar-left" role="search" method="get">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-inverse">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}{{album.album_title}}{% endblock %}

{% block body %}
<img src="{{album.album_logo}}" style="width: 250px;">
<h1>{{album.album_title}}</h1>
<h2>{{album.artist}}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

{% for song in album.song_set.all %}
    {{ song.song_title }}
    {% if song.is_favourite %}
        <img src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/16/star-icon.png" />
    {% endif %}
    <br>
{% endfor %}

<!--<form action="{% url 'music:favourite' album.id %}", method="post">-->
    <!--{% csrf_token %}-->
    <!--{% for song in album.song_set.all %}-->
        <!--<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">-->
    <!--<label for="song{{ forloop.counter }}">-->
        <!--{{ song.song_title }}-->
        <!--{% if song.is_favourite %}-->
            <!--<img src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/16/star-icon.png" />-->
        <!--{% endif %}-->
    <!--</label><br>-->
    <!--{% endfor %}-->
    <!--<input type="submit" value = "Favourite">-->
<!--</form>-->
<!--<ul>-->
    <!--{%for song in album.song_set.all%}-->
        <!--<li>{{song.song_title}} - {{song.file_type}}</li>-->
    <!--{%endfor%}-->
<!--</ul>-->

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
<div class="container">
    <!--<h1 ><font color="#70d194">WELCOME TO THE MUSIC APP!!</font></h1><br>-->
    {% if all_albums %}
    <!--<h2><font color="#2056c1">Here is a list of your albums</font></h2>-->
    <ul>
        {% for album in all_albums%}
        <li><a href="{% url 'music:details' album.id %}">{{album.album_title}}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <h3>You don't have any albums</h3>
    {% endif %}
</div>
{% endblock %}